import '/styles/globals.css'
import { Poppins } from 'next/font/google'
import Header from '/components/Header'
import Footer from '/components/Footer'
import api from '@/libs/api'

const poppins = Poppins({ subsets: ['latin'], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export let myConfig = {}
export let mediumProfile = {}

async function getConfig() {
  return await api({page: "config"})
}

async function getMediumProfile() {
  return await api({
    page: 'https://api.medium.com/v1/me',
    plain: true,
    token: process.env.MEDIUM_API_TOKEN
  })
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const config = await getConfig()
  myConfig = config.items[0].data

  const medium = await getMediumProfile()
  mediumProfile = medium.data

  return (
    <html lang="en">
      <body className={poppins.className} suppressHydrationWarning={true}>
        <div className="mx-auto">
          {/* Navbar */}
          <Header config={config} />
          {/* End of Navbar */}

          {/* Content */}
          {children}
          {/* End of Content */}
          
          {/* Footer */}
          <Footer />
          {/* End of Footer */}
        </div>
      </body>
    </html>
  )
}
